# 11.07.2017
japanese_car_brands = []
japanese_car_brands.append('honda')
japanese_car_brands.append('lexus')
japanese_car_brands.append('mazda')
japanese_car_brands.append('mitsubishi')
japanese_car_brands.append('nissan')
japanese_car_brands.append('subaru')
japanese_car_brands.append('toyota')
japanese_car_brands.append('acura')
print("Japanese car brands: ")
print(japanese_car_brands)
print("\nAlphabetical order: ")
print(sorted(japanese_car_brands))
print("\nReverse alphabetical order: ")
print(sorted(japanese_car_brands, reverse=True))
print("\nLenght of a Japanese car brands: " + str(len(japanese_car_brands)))
