# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20170928_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='name',
            new_name='text',
        ),
    ]
