names = ["Anna", "Cameron", "Jeen", "Daniela", "Trixie"]
print(names[0])
print(names[1])
print(names[2])
print(names[3])
print(names[4])
print(names[0] + " likes to look at the stars in the night sky.")
print(names[1] + " likes to look at the stars in the night sky.")
print(names[2] + " likes to look at the stars in the night sky.")
print(names[3] + " likes to look at the stars in the night sky.")
print(names[4] + " likes to look at the stars in the night sky.")
